modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_enchantment_industry"
version="${file.jarVersion}"
displayName="Create Enchantment Industry"
logoFile="pack.png"
authors="MarbleGateKeeper & LimonBlaze"
description='''
Automatic Enchanting, with Create.
'''

[[dependencies.create_enchantment_industry]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_enchantment_industry]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.create_enchantment_industry]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="create_enchantment_industry.mixins.json"
